In [1]:
import argparse
import cProfile as profile
import glob
import os

import cv2
import numpy as np
import pandas as pd
import scipy.io as sio

from metrics.stats_utils import (
    get_dice_1,
    get_fast_aji,
    get_fast_aji_plus,
    get_fast_dice_2,
    get_fast_pq,
    remap_label,
    pair_coordinates
)


def run_nuclei_type_stat(pred_dir, true_dir, type_uid_list=None, exhaustive=True):
    """GT must be exhaustively annotated for instance location (detection).

    Args:
        true_dir, pred_dir: Directory contains .mat annotation for each image. 
                            Each .mat must contain:
                    --`inst_centroid`: Nx2, contains N instance centroid
                                       of mass coordinates (X, Y)
                    --`inst_type`    : Nx1: type of each instance at each index
                    `inst_centroid` and `inst_type` must be aligned and each
                    index must be associated to the same instance
        type_uid_list : list of id for nuclei type which the score should be calculated.
                        Default to `None` means available nuclei type in GT.
        exhaustive : Flag to indicate whether GT is exhaustively labelled
                     for instance types
                     
    """
    file_list = glob.glob(pred_dir + "*.mat")
    file_list.sort()  # ensure same order [1]

    paired_all = []  # unique matched index pair
    unpaired_true_all = []  # the index must exist in `true_inst_type_all` and unique
    unpaired_pred_all = []  # the index must exist in `pred_inst_type_all` and unique
    true_inst_type_all = []  # each index is 1 independent data point
    pred_inst_type_all = []  # each index is 1 independent data point
    for file_idx, filename in enumerate(file_list[:]):
        filename = os.path.basename(filename)
        basename = filename.split(".")[0]

        true_info = sio.loadmat(os.path.join(true_dir, basename + ".mat"))
        # dont squeeze, may be 1 instance exist
        true_centroid = (true_info["inst_centroid"]).astype("float32")
        true_inst_type = (true_info["inst_type"]).astype("int32")

        if true_centroid.shape[0] != 0:
            true_inst_type = true_inst_type[:, 0]
        else:  # no instance at all
            true_centroid = np.array([[0, 0]])
            true_inst_type = np.array([0])

        # * for converting the GT type in CoNSeP
        # true_inst_type[(true_inst_type == 3) | (true_inst_type == 4)] = 3
        # true_inst_type[(true_inst_type == 5) | (true_inst_type == 6) | (true_inst_type == 7)] = 4

        pred_info = sio.loadmat(os.path.join(pred_dir, basename + ".mat"))
        # dont squeeze, may be 1 instance exist
        pred_centroid = (pred_info["inst_centroid"]).astype("float32")
        pred_inst_type = (pred_info["inst_type"]).astype("int32")

        if pred_centroid.shape[0] != 0:
            pred_inst_type = pred_inst_type[:, 0]
        else:  # no instance at all
            pred_centroid = np.array([[0, 0]])
            pred_inst_type = np.array([0])

        # ! if take longer than 1min for 1000 vs 1000 pairing, sthg is wrong with coord
        paired, unpaired_true, unpaired_pred = pair_coordinates(
            true_centroid, pred_centroid, 12
        )

        # * Aggreate information
        # get the offset as each index represent 1 independent instance
        true_idx_offset = (
            true_idx_offset + true_inst_type_all[-1].shape[0] if file_idx != 0 else 0
        )
        pred_idx_offset = (
            pred_idx_offset + pred_inst_type_all[-1].shape[0] if file_idx != 0 else 0
        )
        true_inst_type_all.append(true_inst_type)
        pred_inst_type_all.append(pred_inst_type)

        # increment the pairing index statistic
        if paired.shape[0] != 0:  # ! sanity
            paired[:, 0] += true_idx_offset
            paired[:, 1] += pred_idx_offset
            paired_all.append(paired)

        unpaired_true += true_idx_offset
        unpaired_pred += pred_idx_offset
        unpaired_true_all.append(unpaired_true)
        unpaired_pred_all.append(unpaired_pred)

    paired_all = np.concatenate(paired_all, axis=0)
    unpaired_true_all = np.concatenate(unpaired_true_all, axis=0)
    unpaired_pred_all = np.concatenate(unpaired_pred_all, axis=0)
    true_inst_type_all = np.concatenate(true_inst_type_all, axis=0)
    pred_inst_type_all = np.concatenate(pred_inst_type_all, axis=0)

    paired_true_type = true_inst_type_all[paired_all[:, 0]]
    paired_pred_type = pred_inst_type_all[paired_all[:, 1]]
    unpaired_true_type = true_inst_type_all[unpaired_true_all]
    unpaired_pred_type = pred_inst_type_all[unpaired_pred_all]

    ###
    def _f1_type(paired_true, paired_pred, unpaired_true, unpaired_pred, type_id, w):
        type_samples = (paired_true == type_id) | (paired_pred == type_id)

        paired_true = paired_true[type_samples]
        paired_pred = paired_pred[type_samples]

        tp_dt = ((paired_true == type_id) & (paired_pred == type_id)).sum()
        tn_dt = ((paired_true != type_id) & (paired_pred != type_id)).sum()
        fp_dt = ((paired_true != type_id) & (paired_pred == type_id)).sum()
        fn_dt = ((paired_true == type_id) & (paired_pred != type_id)).sum()

        if not exhaustive:
            ignore = (paired_true == -1).sum()
            fp_dt -= ignore

        fp_d = (unpaired_pred == type_id).sum()
        fn_d = (unpaired_true == type_id).sum()

        f1_type = (2 * (tp_dt + tn_dt)) / (
            2 * (tp_dt + tn_dt)
            + w[0] * fp_dt
            + w[1] * fn_dt
            + w[2] * fp_d
            + w[3] * fn_d
        )
        return f1_type

    # overall
    # * quite meaningless for not exhaustive annotated dataset
    w = [1, 1]
    tp_d = paired_pred_type.shape[0]
    fp_d = unpaired_pred_type.shape[0]
    fn_d = unpaired_true_type.shape[0]

    tp_tn_dt = (paired_pred_type == paired_true_type).sum()
    fp_fn_dt = (paired_pred_type != paired_true_type).sum()

    if not exhaustive:
        ignore = (paired_true_type == -1).sum()
        fp_fn_dt -= ignore

    acc_type = tp_tn_dt / (tp_tn_dt + fp_fn_dt)
    f1_d = 2 * tp_d / (2 * tp_d + w[0] * fp_d + w[1] * fn_d)

    w = [2, 2, 1, 1]

    if type_uid_list is None:
        type_uid_list = np.unique(true_inst_type_all).tolist()

    results_list = [f1_d, acc_type]
    for type_uid in type_uid_list:
        f1_type = _f1_type(
            paired_true_type,
            paired_pred_type,
            unpaired_true_type,
            unpaired_pred_type,
            type_uid,
            w,
        )
        results_list.append(f1_type)

    np.set_printoptions(formatter={"float": "{: 0.5f}".format})
    print(np.array(results_list))
    return


def run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False, ext=".mat"):
    # print stats of each image
    print(pred_dir)

    file_list = glob.glob("%s/*%s" % (pred_dir, ext))
    file_list.sort()  # ensure same order

    metrics = [[], [], [], [], [], []]
    for filename in file_list[:]:
        filename = os.path.basename(filename)
        basename = filename.split(".")[0]
        
        true = sio.loadmat(os.path.join(true_dir, basename + ".mat"))
        true = (true["inst_map"]).astype("int32")

        pred = sio.loadmat(os.path.join(pred_dir, basename + ".mat"))
        pred = (pred["inst_map"]).astype("int32")

        # to ensure that the instance numbering is contiguous
        pred = remap_label(pred, by_size=False)
        true = remap_label(true, by_size=False)
        try:
            pq_info = get_fast_pq(true, pred, match_iou=0.5)[0]
            dice = get_dice_1(true, pred)
            aji = get_fast_aji(true, pred)
            aji_plus = get_fast_aji_plus(true, pred)
            metrics[0].append(dice)
            metrics[1].append(aji)
            metrics[2].append(pq_info[0])  # dq
            metrics[3].append(pq_info[1])  # sq
            metrics[4].append(pq_info[2])  # pq
            metrics[5].append(aji_plus)
        except:
            #print("did not run for", filename)
            continue

        if print_img_stats:
            print(basename, end="\t")
            for scores in metrics:
                print("%f " % scores[-1], end="  ")
            print()
    ####
    metrics = np.array(metrics)
    print(metrics.shape)
    print(metrics)
    metrics_avg = np.mean(metrics, axis=-1)
    np.set_printoptions(formatter={"float": "{: 0.5f}".format})
    print(metrics_avg)
    metrics_avg = list(metrics_avg)
    return metrics




# CoNSeP

In [2]:
if __name__ == "__main__":
    true_dir = r'DATA\CoNSeP\Test\Labels'
    pred_dir = r"test_output\mat"
    
    mode = "instance";
    if mode == "instance":
        run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False)
    if mode == "type":
        run_nuclei_type_stat(pred_dir, true_dir)

test_output\mat
[ 0.84817  0.54631  0.66803  0.77078  0.51617  0.57440]


# PanNuke 

In [19]:
if __name__ == "__main__":
    true_dir = r'dataset\PanNuke\Fold 1\masks\fold1\consep_format'
    pred_dir = r"test_output\PanNuke\mat"
    
    mode = "instance";
    if mode == "instance":
        run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False)
    if mode == "type":
        run_nuclei_type_stat(pred_dir, true_dir)

test_output\PanNuke\mat
did not run for 1001.mat
did not run for 1006.mat
did not run for 1148.mat
did not run for 1149.mat
did not run for 1150.mat
did not run for 1153.mat
did not run for 1155.mat
did not run for 1156.mat
did not run for 1159.mat
did not run for 1161.mat
did not run for 1162.mat
did not run for 1165.mat
did not run for 1167.mat
did not run for 1433.mat
did not run for 1434.mat
did not run for 1513.mat
did not run for 1615.mat
did not run for 1617.mat
did not run for 1618.mat
did not run for 1619.mat
did not run for 1620.mat
did not run for 1621.mat
did not run for 1705.mat
did not run for 1706.mat
did not run for 1708.mat
did not run for 1709.mat
did not run for 1710.mat
did not run for 1724.mat
did not run for 1725.mat
did not run for 1726.mat
did not run for 1749.mat
did not run for 1750.mat
did not run for 1751.mat
did not run for 1752.mat
did not run for 1753.mat
did not run for 1860.mat
did not run for 1881.mat
did not run for 1924.mat
did not run for 1940.mat
d

# New Weights after Retraining with merged data

# CONSEP

In [4]:
if __name__ == "__main__":
    true_dir = r'dataset\CoNSeP\Test\Labels'
    pred_dir = r"test_output\new_retrained_weights\consep_new\mat"
    
    mode = "instance";
    if mode == "instance":
        run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False)
    if mode == "type":
        run_nuclei_type_stat(pred_dir, true_dir)

test_output\new_retrained_weights\consep_new\mat
(6, 14)
[[ 0.85906  0.84276  0.85231  0.84266  0.85212  0.79813  0.77090  0.87562
   0.88604  0.82256  0.86871  0.81239  0.86988  0.83922]
 [ 0.53889  0.58563  0.44516  0.62305  0.53209  0.60021  0.51685  0.58422
   0.58612  0.51957  0.54445  0.47920  0.48632  0.53758]
 [ 0.70254  0.73469  0.49383  0.75878  0.66981  0.73112  0.64646  0.66038
   0.66741  0.71506  0.65819  0.57286  0.59969  0.70160]
 [ 0.76518  0.78569  0.74569  0.76924  0.78885  0.79487  0.74375  0.77812
   0.77335  0.76863  0.78510  0.73460  0.74960  0.78261]
 [ 0.53756  0.57724  0.36824  0.58368  0.52838  0.58115  0.48081  0.51386
   0.51614  0.54961  0.51674  0.42082  0.44953  0.54909]
 [ 0.58749  0.60596  0.53719  0.65947  0.59459  0.60794  0.52478  0.60657
   0.61281  0.57381  0.56500  0.50452  0.51996  0.57645]]
[ 0.84231  0.54138  0.66517  0.76895  0.51235  0.57690]


# PanNuke

In [5]:
if __name__ == "__main__":
    true_dir = r'dataset\PanNuke\Fold 1\masks\fold1\consep_format'
    pred_dir = r"test_output\new_retrained_weights\pannuke_new\mat"
    
    mode = "instance";
    if mode == "instance":
        run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False)
    if mode == "type":
        run_nuclei_type_stat(pred_dir, true_dir)

test_output\new_retrained_weights\pannuke_new\mat
(6, 2545)
[[ 0.76683  0.84613  0.80593 ...  0.06265  0.00000  0.72194]
 [ 0.58158  0.67018  0.60852 ...  0.03234  0.00000  0.56487]
 [ 0.66667  0.66667  0.72222 ...  0.00000  0.00000  0.50000]
 [ 0.80574  0.82857  0.79410 ...  0.00000  0.00000  0.84433]
 [ 0.53716  0.55238  0.57352 ...  0.00000  0.00000  0.42216]
 [ 0.58158  0.69118  0.60852 ...  0.03234  0.00000  0.56487]]
[ 0.81678  0.65151  0.75846  0.80855  0.62407  0.66314]


# Combined Data

In [2]:
if __name__ == "__main__":
    true_dir = r'dataset\training_data\combined\test\mat'
    pred_dir = r"test_output\new_retrained_weights\combined_test_new\mat"
    
    mode = "instance";
    if mode == "instance":
        run_nuclei_inst_stat(pred_dir, true_dir, print_img_stats=False)
    if mode == "type":
        run_nuclei_type_stat(pred_dir, true_dir)

test_output\new_retrained_weights\combined_test_new\mat
(6, 2274)
[[0.92208241 0.86351246 0.90725511 ... 0.43432959 0.93043478 0.7772779 ]
 [0.84344583 0.65677419 0.78668765 ... 0.27740806 0.82042042 0.63569465]
 [0.88372093 0.60869565 0.80769231 ... 0.4        0.86363636 0.76923077]
 [0.87882373 0.8127107  0.85715272 ... 0.72794817 0.88104459 0.77783929]
 [0.77663492 0.49469347 0.69231566 ... 0.29117927 0.76090215 0.59833792]
 [0.84344583 0.65677419 0.79256067 ... 0.27740806 0.82494421 0.63569465]]
[ 0.80804  0.63882  0.74415  0.80355  0.61069  0.65023]
